workshop/pets/urls.py
from django.urls import path

from pets.views import list_pets, details_or_comment_pet, like_pet, create_pet, edit_pet, delete_pet

urlpatterns = [
    path('', list_pets, name='list pets'),
    path('detail/<int:pk>', details_or_comment_pet, name='pet details or comment'),
    path('like/<int:pk>', like_pet, name='like pet'),
    path('create/', create_pet, name='create pet'),
    path('edit/<int:pk>', edit_pet, name='edit pet'),
    path('delete/<int:pk>', delete_pet, name='delete pet'),
]

workshop/petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('pets/', include('pets.urls')),
    path('users/', include('users.urls')),
]

workshop/pets/models.py
from django.db import models


# Create your models here.
class Pet(models.Model):
    DOG = 'dog'
    CAT = 'cat'
    PARROT = 'parrot'
    UNKNOWN = 'unknown'

    PET_TYPES = (
        (DOG, 'Dog'),
        (CAT, 'Cat'),
        (PARROT, 'Parrot'),
        (UNKNOWN, 'Unknown'),
    )
    type = models.CharField(max_length=7, choices=PET_TYPES, default=UNKNOWN)
    name = models.CharField(max_length=6, blank=False)
    age = models.IntegerField(blank=False)
    description = models.TextField(blank=False)
    image_url = models.URLField(blank=False)

    def __str__(self):
        return f'{self.id} {self.name} {self.age}'


class Like(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    test = models.CharField(max_length=2)


class Comment(models.Model):
    # Cascade - If the pet is deleted, the Comment will be also removed!!!
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    text = models.TextField(blank=False)

workshop/users/forms/login_form.py
from django import forms


class LoginForm(forms.Form):
    pass

workshop/users/forms/register_form.py
from django import forms


class RegisterForm(forms.Form):
    pass

workshop/templates/landing_page.html
{% extends 'shared/base.html' %}
{% block site_content %}
    <div class="jumbotron parent">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="absolute">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="inner cover">
                <h1 class="cover-heading"></h1>
                <div class="row">
                    <div class="col-lg-6">
                        <p class="lead">Already have an account? <br>
                            <div><a href="{% url 'login' %}" class="btn btn-lg btn-secondary">sign in</a></div>
                        </p>
                    </div>
                    <div class="col-lg-6">
                        <p class="lead"> Do not have an account? <br>
                            <div><a href="{% url 'register' %}" class="btn btn-lg btn-secondary">sign up</a></div>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

workshop/templates/login.html
{% extends 'shared/base.html' %}

{% block title %} | Account Login {% endblock %}


{% block site_content %}
    <section id="login" class="bg-light py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h4><i class="fas fa-sign-in-alt"></i> Login</h4>
                        </div>
                        <div class="card-body">
                            <!-- Alerts -->
                            {% include 'partials/_alerts.html' %}
                            <form method="POST" action="{% url 'login' %}" >
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input type="text" name="username" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="password2">Password</label>
                                    <input type="password" name="password" class="form-control" required>
                                </div>

                                <input type="submit" value="Login" class="btn btn-secondary btn-block">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

workshop/templates/pet_create.html
{% extends 'shared/base.html' %}
{% block site_content %}

    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="furniture-form">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

workshop/templates/pet_delete.html
{% extends 'shared/base.html' %}
{% block site_content %}

    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete {{ pet.name }}?</h1>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post" action="{% url 'delete pet' pet.id%}">
                        {% csrf_token %}
{#                        <button type="submit" value="Confirm" class="btn btn-danger">#}
                        <button class="btn btn-danger">
                            Confirm
                        </button>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

workshop/templates/pet_detail.html
{% extends 'shared/base.html' %}
{% block site_content %}

    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <img src="{{ pet.image_url }}" class="w-50 rounded mx-auto d-block">
        </div>
        <div class="d-inline p-2 w-50">
            <div class="d-flex justify-content-between">
                <h5><u>Type:</u> {{ pet.type }}</h5>
                <h5><u>Name:</u> {{ pet.name }}</h5>
                <h5><u>Age:</u> {{ pet.age }}</h5>
            </div>
            <p class="mt-2">Description: {{ pet.description }}</p>
            <a href="{% url 'edit pet' pet.id %}" class="btn btn-success">Edit</a>
            <a href="{% url 'delete pet' pet.id %}" class="btn btn-danger">Delete</a>
            <hr>
            <div>
                <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
            </div>
            <p class="mt-2">Likes: {{ pet.like_set.count }}</p>
        </div>
    </div>
    <div class="d-block" style="background-color: #f1e3e3; padding: 2%">
        {% if pet.comment_set.count > 0 %}
            {% for comment in pet.comment_set.all %}
                <div class="box">
                    <h5><em>{{ comment.text }}</em></h5>
                    <hr>
                </div>
            {% endfor %}
        {% else %}
            <div class="box">
                <h3>There are no comments for this pet. </h3>
            </div>
        {% endif %}
        <div class="box">
            <form method="post" action="{% url 'pet details or comment' pet.id %}">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Add comment</button>
            </form>
        </div>

    </div>
{% endblock %}

workshop/templates/pet_edit.html
{% extends 'shared/base.html' %}
{% block site_content %}

    <h1 class="text-center">Edit pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="furniture-form" action="{% url 'edit pet' pet.id %}">
                {{ form }}
                {% csrf_token %}
                <img id="img_preview" src="{{ pet.image_url }}" class="card-img-top" alt="..."/>
                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <script>
        function updateImage() {
            var img = document.getElementById('img_preview');
            var new_url = this.value;
            img.src = new_url;
        }

        document.getElementById('img_input')
            .addEventListener('input', updateImage);
    </script>
{% endblock %}

workshop/templates/pet_list.html
{% extends 'shared/base.html' %}
{% block site_content %}

    <h1 class='text-center'>All pet photos</h1>
    <div class="row">
        {% for pet in pets %}

            <div class="col-lg-4">
            <div class="card" style="width: 18rem;">
                <img src="{{ pet.image_url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</h5>
                    <p class="card-text">{{ pet.description }}</p>
                    <a href="{% url 'pet details or comment' pet.id %}" class="btn btn-primary">See details</a>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
{% endblock %}

workshop/templates/register.html
{% extends 'shared/base.html' %}

{% block title %} | Register account {% endblock %}

{% block site_content %}
    <section id="register" class="bg-light py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h4><i class="fas fa-user-plus"></i> Register</h4>
                        </div>
                        <div class="card-body">
                            <!-- Alerts -->
                            {% include 'partials/_alerts.html' %}
                            <form method="POST" action="{% url 'register' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="first_name">First Name</label>
                                    <input type="text" name="first_name" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="last_name">Last Name</label>
                                    <input type="text" name="last_name" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input type="text" name="username" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" name="email" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="password2">Password</label>
                                    <input type="password" name="password" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="password">Confirm Password</label>
                                    <input type="password" name="password2" class="form-control" required>
                                </div>
                                <input type="submit" value="Register" class="btn btn-secondary btn-block">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}