django102/django102/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django102_admin.urls')),
    path('', include('django103_app.urls')),
]

django102/django102_admin/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django102/django103_app/urls.py
from django.urls import path

from django103_app.views import index, GamesListView, create_game

urlpatterns = [
    path('', index, name='index'),
    path('games/', GamesListView.as_view()),
    path('create_game/', create_game),
]

django102/django102_admin/models.py
from django.db import models

# Create your models here.

django102/django103_app/models/game.py
from django.db import models

# Create your models here.
from django103_app.models.player import Player


class GameManager(models.Manager):
    def all_with_players_count(self):
        games = self.all() \
            .annotate(players_count=models.Count('players'))
        return games


class Game(models.Model):
    objects = GameManager()

    EASY = 1
    MEDIUM = 2
    HARD = 3

    DIFFICULTY_LEVEL_CHOICES = (
        (EASY, 'Easy'),
        (MEDIUM, 'Medium'),
        (HARD, 'Hard'),
    )

    name = models.CharField(max_length=20, blank=False, default='')
    level_of_difficulty = models.IntegerField(
        blank=False,
        choices=DIFFICULTY_LEVEL_CHOICES,
        default=MEDIUM,
    )
    players = models.ManyToManyField(Player)

    def __str__(self):
        return f'{self.name}'

django102/django103_app/models/person.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=20, blank=False)
    last_name = models.CharField(max_length=20, blank=False)
    age = models.IntegerField(default=0, blank=False)

django102/django103_app/models/player.py
from django.contrib.auth.models import User
from django.db import models


class Player(models.Model):
    nickame = models.CharField(max_length=20, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nickame}'

django102/django102_admin/views.py
from django.shortcuts import render

# Create your views here.

django102/django103_app/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.generic import ListView

from django103_app.models.game import Game
from django103_app.models.player import Player
from django103_app.models.person import Person


# Create your views here.
def index(request):
    users = User.objects.all()
    games = Game.objects.all()

    context = {
        'users_list': users,
        'games_list': games,
    }
    return render(request, 'index.html', context)


class GamesListView(ListView):
    model = Game
    template_name = 'games.html'

    # Sorting games by name in asc order
    queryset = Game.objects.all().order_by('name')


def create_game(request):
    game = Game(
        name='Video',
        level_of_difficulty=Game.MEDIUM,
    )
    game.save()
    return redirect('index')

django102/templates/games.html
{% extends 'shared/base.html' %}
{% load static %}

{% block page_styles %}
    <link rel="stylesheet" href="{% static 'css/demo.css' %}">
{% endblock %}

{% block site_title %}
    GAMES PAGE
{% endblock %}


{% block site_content %}
    <h1>GAMES PAGE WITH CLASS VIEW WORKS FINE!</h1>
    <ul>
        {% for game in object_list %}
            <li>
                {{ game.name }}
                {{ game.level_of_difficulty }}
                {{ game.get_level_of_difficulty_display }}
                {{ game.players_count }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

django102/templates/index.html
{% extends 'shared/base.html' %}
{% load static %}


{% block site_title %}
    INDEX PAGE
{% endblock %}

{##}
{#{% block site_content %}#}
{#    <h1>INDEX PAGE WITH FUNCTIONAL VIEW WORKS FINE</h1>#}
{#    {% if users_list %}#}
{#        <ul>#}
{#            {% for user in users_list %}#}
{#                <li class="highlightable">#}
{#                    {{ user.username }}#}
{#                </li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% else %}#}
{#        No users#}
{#    {% endif %}#}
{#{% endblock %}#}